###
GET https://water-dispenser.herokuapp.com/rfids
Authorization: Basic Z3V5OjEyMzQ1 

###
GET https://water-dispenser.herokuapp.com/rfids/7B1CB1281
Authorization: Basic Z3V5OjEyMzQ1 

###
GET http://localhost:5000/rfids
Authorization: Basic Z3V5OjEyMzQ1 

###
GET http://localhost:5000/rfids/7B1CB128
Authorization: Basic Z3V5OjEyMzQ1 

###
GET http://localhost:5000/trans
Authorization: Basic Z3V5OjEyMzQ1

###
GET http://localhost:5000/trans/filtered
Authorization: Basic Z3V5OjEyMzQ1
Content-Type: application/json

{
    "limit": 2,
    "dateFrom": "2022-07-01",
    "dateTo": "2022-08-01"
}

###
POST http://localhost:5000/trans
Authorization: Basic Z3V5OjEyMzQ1 
Content-Type: application/json

{
    "cardID" : "123456ABC",
    "amount" : 250,
    "transType": "Purchase"
}